# Extracción de datos

En un inicio, la extracción de datos se realizaba por medio de la interfaz de programación de aplicaciones (API, por sus siglas en inglés) del banco de datos de proteínas (PDB, por sus siglas en inglés), con ayuda de un formato en `.xml` autogenerado en base a una búsqueda avanzada en el mismo sitio del PDB. Sin embargo, la descontinuación de esta API para ser reemplazada por una mejor (información [aquí](https://www.rcsb.org/news?year=2020&article=5eb18ccfd62245129947212a&feature=true)) terminó con este proceso. 

Por el motivo anterior y puesto que la nueva API no se encuentra del todo completa, se decidió emplear la información cruda del PDB, es decir, los archivos de las estructuras en `.pdb` o `.mmCIF`. Cabe recalcar que el formato `.mmCIF`, tiene como fin reemplazar el formato `.pdb` (información [aquí](http://mmcif.wwpdb.org/docs/faqs/pdbx-mmcif-faq-general.html)). De hecho, desde abril del 2019, es indispensable depositar la estructura resuelta en formato `.mmCIF` (información [aquí](https://journals.iucr.org/d/issues/2019/04/00/rr5177/)).

## PDB
Para descargar todo las estructuras del PDB en formato `.mmCIF`, se usa el siguiente comando:

```{bash, eval=FALSE}
cd /run/media/murphy/lolita
rsync -rlpt -v -z --delete --port=33444 \
rsync.rcsb.org::ftp_data/structures/divided/mmCIF/ ./mmCIF
```

> Instrucciones de [aquí](https://www.wwpdb.org/ftp/pdb-ftp-sites).

Para las pruebas se hace una copia de este directorio.

```{bash, eval=FALSE}
cp -r mmCIF/ testing
```